# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e30f4038a4f3eff23acd3e83d56c3f1e"
name = "townwine-follow"
application_url = "https://townwine-follow.onrender.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/create"
  topics = [ "products/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/products/update"
  topics = [ "products/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/metafields/create"
  topics = [ "metafields/create" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/metafields/update"
  topics = [ "metafields/update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
scopes = "read_content,read_customers,read_metaobject_definitions,read_metaobjects,read_orders,read_products,write_app_proxy,write_content,write_metaobject_definitions,write_metaobjects,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://townwine-follow.onrender.com/auth/callback" ]

[app_proxy]
url = "/apps/townwine-follow"
subpath = "townwine-follow"
prefix = "apps"
